config/routes.rb
CIRCL::Application.routes.draw do

  get 'requires_browser_update' => 'settings#requires_browser_update'

  unauthenticated :person do
    devise_scope :person do
      get "/" => "devise/sessions#new"
    end
  end

  authenticated :person do
    root :to => 'people#welcome'
  end

  devise_for :people
  resources  :people do
    member do
      get 'change_password', 'map'
      post 'update_password', 'unlock'
      put 'update_password'
    end

    collection do
      get 'paginate', 'search', 'title_search', 'nationality_search', 'duplicates_report'
    end

    resources :dashboard, :controller => 'people/dashboard', :only => :index do
      collection do
        get 'comments', 'activities', 'last_people_added', 'open_invoices', 'current_affairs',
          'open_salaries'
      end
    end

    resources :activities, :controller => 'people/activities'
    resources :histories, :controller => 'people/histories'

    resources :affairs, :controller => 'people/affairs' do
      collection do
        get 'search', 'count', 'affairs', 'invoices', 'receipts'
      end

      resources :extras, :controller => 'people/affairs/extras' do
        collection do
          get 'count', 'change_order'
        end
      end

      resources :invoices, :controller => 'people/affairs/invoices' do
        member do
          get 'bvr_preview'
        end

        collection do
          get 'search'
        end
      end

      resources :products, :controller => 'people/affairs/products' do
        collection do
          get 'search', 'change_position', 'categories'
          post 'reorder', 'group_update'
          delete 'group_destroy'
        end
      end

      resources :product_categories,
        controller: "people/affairs/product_categories",
        only: [:index] do

        collection do
          post 'update'
        end

      end

      resources :receipts,
        controller: 'people/affairs/receipts'

      delete 'communication_languages' => 'people/subscriptions#destroy' # Spine

      resources :subscriptions,
        controller: 'people/affairs/subscriptions'

      resources :tasks,
        controller: 'people/affairs/tasks'
    end

    resources :comments, :controller => 'people/comments' do
      collection do
        get 'count'
      end
    end

    put 'communication_languages' => 'people/communication_languages#update' # Spine
    resources :communication_languages, :controller => 'people/communication_languages', :only => :index do
    end

    resources :employment_contracts, :controller => 'people/employment_contracts'

    put 'private_tags' => 'people/private_tags#update' # Spine
    resources :private_tags, :controller => 'people/private_tags', :only => :index do
    end

    put 'public_tags' => 'people/public_tags#update' # Spine
    resources :public_tags, :controller => 'people/public_tags', :only => :index do
    end

    put 'roles' => 'people/roles#update' # Spine
    resources :roles, :controller => 'people/roles', :only => :index do
    end

    resources :salaries, :controller => 'people/salaries/salaries' do
      member do
        put 'update_items', 'update_tax_data'
      end

      collection do
        post 'statistics'
      end

      resources :items, :controller => 'people/salaries/items', :only => [ :index ] do
        member do
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end

      resources :tax_data, :controller => 'people/salaries/tax_data', :only => [ :index ] do
        member do
          put 'reset'
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end
    end

    resources :tasks, :controller => 'people/tasks'
  end

  get 'salaries' => 'salaries#index'
  namespace :salaries do
    resources :salaries, :except => [:edit] do
      member do
        post 'copy_reference'
      end
      collection do
        get 'pending', 'export', 'export_accounting', 'export_ocas', 'export_certificates', 'available_years'
      end
    end

    resources :taxes do
      member do
        post 'import_data'
      end
      collection do
        get 'models', 'count'
      end
    end
  end

  match 'directory' => 'directory#index', :via => [:get, :post]
  post 'directory/:id/mailchimp' => 'directory#mailchimp'
  get 'directory/map' => 'directory#map'
  post 'directory/confirm_people' => 'directory#confirm_people'
  post 'directory/import_people' => 'directory#import_people'
  namespace :directory do
    resources :query_presets
  end

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :affairs do
      collection do
        get 'search', 'available_statuses'
        post 'check_items', 'uncheck_items', 'archive_items'
      end
    end

    resources :bank_import_histories, :only => :index do
      collection do
        post 'confirm', 'import'
        get 'export'
      end
    end

    resources :creditors, defaults: { format: 'json' } do
      collection do
        get 'export', format: 'html'
        post 'check_items', 'uncheck_items', 'group_update'
        post 'preview_import', 'import', format: 'html'
        delete 'group_destroy'
      end
    end

    resources :invoices do
      collection do
        get 'export', 'available_statuses', 'search'
      end
    end

    resources :private_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :product_orders, only: [:index]

    resources :public_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :receipts do
      collection do
        get 'export', 'means_of_payments', 'documents'
        post 'documents'
      end
    end

    resources :subscriptions do
      member do
        # POST on show is required for the PDF generation from the search engine
        post 'add_members', 'transfer_overpaid_value', 'show', 'merge'
        delete 'remove_members'
      end
      collection do
        put 'tag_tool'
        get 'search', 'count'
      end
    end

  end

  resources :background_tasks, :only => [:index, :destroy]

  resources :settings, :only => :index do
    collection do
      get 'requires_browser_update'
    end
  end
  namespace :settings do
    resources :application_settings do
      collection do
        post 'restart'
      end
    end

    resources :affairs_conditions

    resources :currencies do
      collection do
        get 'search'
      end
    end

    resources :currency_rates do
      collection do
        get 'exchange'
      end
    end

    resources :generic_templates do
      collection do
        get 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :invoice_templates do
      collection do
        get 'placeholders', 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :jobs do
      collection do
        get 'search'
      end
    end

    resources :languages

    resources :ldap_attributes do
      collection do
        post 'synchronize'
      end
    end

    resources :locations do
      collection do
        get 'search'
      end
    end

    resources :permissions, :only => :index

    resources :products do
      collection do
        get 'search', 'count', 'category_search'
        post 'preview_import', 'import'
      end
      member do
        get 'programs'
      end
    end

    resources :product_programs do
      collection do
        get 'program_groups', 'program_group_search', 'search', 'count'
        post 'preview_import', 'import'
      end
    end

    resources :roles do
      resources :permissions, :controller => 'roles/permissions'
    end

    resources :search_attributes do
      collection do
        get 'searchable'
        post 'synchronize'
      end
    end

    # resources :tasks
    resources :task_types
    resources :task_rates

  end

  resources :permissions, :only => :index, :controller => 'people/permissions'

end

app/controllers/people/affairs/extras_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class People::Affairs::ExtrasController < ApplicationController

  layout false

  load_resource :person
  load_resource :affair
  load_and_authorize_resource through: :affair

  def index

    @affair = Affair.find(params[:affair_id])
    @extras = @affair.extras

    if params[:template_id]
      @affair.template = GenericTemplate.find params[:template_id]
    end

    respond_to do |format|
      format.json { render json: @extras }

      format.csv do
        fields = []
        fields << 'id'
        fields << 'position'
        fields << 'quantity'
        fields << 'title'
        fields << 'description'
        fields << 'value'
        fields << 'created_at'
        fields << 'updated_at'
        render inline: csv_ify(@extras, fields)
      end

      if params[:template_id]
        format.html do
          generator = AttachmentGenerator.new(@affair)
          render inline: generator.html, layout: 'preview'
        end

        format.pdf do
          @pdf = ""
          generator = AttachmentGenerator.new(@affair)
          generator.pdf { |o,pdf| @pdf = pdf.read }
          send_data @pdf,
                    filename: "affair_extras_#{params[:affair_id]}.pdf",
                    type: 'application/pdf'
        end

        format.odt do
          @odt = ""
          generator = AttachmentGenerator.new(@affair)
          generator.odt { |o,odt| @odt = odt.read }
          send_data @odt,
                    filename: "affair_extras_#{params[:affair_id]}.odt",
                    type: 'application/vnd.oasis.opendocument.text'
        end
      end
    end
  end

  def show
    edit
  end

  def create
    @extra = @affair.extras.new(extra_params)
    @extra.value = Money.new(params[:value].to_f * 100, params[:value_currency])
    @extra.vat = Money.new(params[:vat].to_f * 100, params[:value_currency])
    respond_to do |format|
      if @extra.save
        format.json { render json: @extra }
      else
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.json { render json: @extra }
    end
  end

  def update
    @extra.value = Money.new(params[:value].to_f * 100, params[:value_currency])
    @extra.vat = Money.new(params[:vat].to_f * 100, params[:value_currency])
    respond_to do |format|
      if @extra.update_attributes(extra_params)
        format.json { render json: @extra }
      else
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @extra.destroy
        format.json { render json: {} }
      else
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  def count
    respond_to do |format|
      format.json { render json: { count: @affair.extras.count } }
    end
  end

  def change_order
    authorize! :update, @person => Extra
    @extras = Extra.find(params[:id])
    success = false

    Extra.transaction do
      siblings = @affair.extras.order(:position).map(&:id)
      id = siblings.delete_at params[:fromPosition].to_i - 1
      siblings.insert(params[:toPosition].to_i - 1, id)
      siblings.delete(nil) # If there is holes in list they will be replace by nil
      siblings.each_with_index do |s, i|
        u = Extra.find(s)
        u.position = i + 1
        u.save!
      end

      success = true
    end

    respond_to do |format|
      if success
        format.json { render json: @affair.extras.all }
      else
        format.json { render json: @extras.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def extra_params
      params.require(:extra).permit(
        :affair_id,
        :title,
        :description,
        :value_in_cents,
        :value_currency,
        :quantity,
        :position,
        :created_at,
        :updated_at,
        :vat_in_cents,
        :vat_currency,
        :vat_percentage
        )
    end
end

app/controllers/people/affairs/product_categories_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class People::Affairs::ProductCategoriesController < ApplicationController

  layout false

  load_resource :person
  load_resource :affair

  def self.model
    AffairsProductsCategory
  end

  def index
    authorize! :index, AffairsProductsCategory
    @categories = @affair.product_categories.order(:position)

    respond_to do |format|
      format.json do
        render json: @categories
      end
    end
  end

  def update
    authorize! :manage, AffairsProductsCategory

    success = false

    AffairsProductsCategory.transaction do
      params[:ids].each_with_index do |c, i|
        AffairsProductsCategory.find(c).update_attributes(position: i + 1)
      end
      success = true
    end

    respond_to do |format|
      if success
        format.json { render json: @categories }
      else
        format.json { render json: "Unable to update order", status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/people/affairs/subscriptions_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class People::Affairs::SubscriptionsController < ApplicationController

  layout false

  load_resource :person
  load_resource :affair

  monitor_changes :@affair

  def self.model
    AffairsSubscription
  end

  def index
    authorize! :index, self.class.model
    @subscriptions = @affair.subscriptions

    respond_to do |format|
      format.json do
        subs = []
        @subscriptions.map do |s|
          h = s.to_hash
          # Add current value for this person
          h[:value] = s.value_for(@affair.person_for_subscription_value).to_f
          h[:value_currency] = s.value_for(@affair.person_for_subscription_value).currency.try(:iso_code)
          subs << h
        end
        render json: subs
      end
    end
  end

  def create
    authorize! :create, @affair => self.class.model

    respond_to do |format|
      if ! params[:subscription_id].empty?
        subscription = Subscription.find params[:subscription_id]
        @affair.subscriptions << subscription

        format.json { render json: subscription }
      else
        format.json { render json: { subscription_id: [I18n.t('activerecord.errors.messages.blank')] }, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    authorize! :destroy, @affair => self.class.model
    @affair.subscription_ids -= [params[:id].to_i]
    respond_to do |format|
      format.json { render json: {} }
    end
  end

end

app/views/people/_header.html.haml
#secondary_navbar.navbar.navbar-default.navbar-static-top

  .navbar-header
    .visible-xs
      .navbar-brand
        #tab_name

    // extra-small resolutions
    %button{class: 'navbar-toggle', 'data-toggle' => 'collapse', 'data-target' => '#secondary_navigation'}
      .icon-bar
      .icon-bar
      .icon-bar

  .container
    #secondary_navigation.collapse.navbar-collapse
      %ul#sub_nav.nav.navbar-nav
        - if can? :read, @person
          %li
            %a{href: '#info_tab'}
              - if @person.new_record?
                %i
                  = I18n.t("person.views.new_contact")
              - else
                = @person.name

        - if can? :read, Affair and @person.id
          %li
            %a{href: '#affairs_tab'}
              = I18n.t('person.views.affairs')
              .badge= @person.affairs.empty? ? nil : @person.affairs.alive.count

        - if can? :read, Salaries::Salary and @person.id
          %li
            %a{href: '#salaries_tab'}
              = I18n.t('person.views.salaries')
              .badge= @person.salaries.empty? ? nil : @person.salaries.count

        - if can? :read, Role and @person.id
          %li
            %a{href: '#permissions_tab'}
              = I18n.t('person.views.permissions')
              .badge= @person.roles.empty? ? nil : @person.roles.count

        - if can? :read, Activity and @person.id
          %li
            %a{href: '#activities_tab'}
              = I18n.t('person.views.activities')
              .badge= @person.comments_edited_by_others.empty? ? nil : @person.comments_edited_by_others.count

      // navbar-right doesn't pull buttons when resolition is XS. Forcing it with pull-right
      .pull-right
        .navbar-right.btn-group
          - if can? :change_password, @person and ! @person.new_record?
            - classes = %w(btn btn-default navbar-btn)
            - classes << 'btn-warning' unless @person.locked_at.nil?
            = link_to unlock_person_path(@person),
                method: 'post',
                class: classes,
                disabled: @person.locked_at.nil? do
              .icon-unlock
              .hidden-inline-sm.hidden-inline-xs
                = I18n.t('person.views.unlock_account')

          - if can? :change_password, @person and ! @person.new_record?
            = link_to change_password_person_path(@person),
                class: 'btn btn-default navbar-btn' do
              .icon-key
              .hidden-inline-sm.hidden-inline-xs
                = I18n.t('person.views.change_password')


          - if can? :destroy, @person and ! @person.new_record?
            = link_to person_path(@person),
                method: :delete,
                data: { confirm: I18n.t('common.are_you_sure') },
                class: 'btn btn-danger navbar-btn' do
              .icon-remove
              .hidden-inline-sm.hidden-inline-xs
                = I18n.t('person.views.destroy')

app/views/people/change_password.html.haml
= render partial: 'header'

.container
  .row
    .col-lg-3
    .col-lg-6
      .panel.panel-primary
        .panel-heading
          .panel-title
            - if @current_person.id == @person.id
              = I18n.t('person.views.change_password')
            - else
              != I18n.t('person.views.change_password_for', person: @person.name)

        .panel-body
          = form_for @person, url: update_password_person_path(@person), method: 'post' do |p|
            .row
              .col-lg-12
                .validation_errors_placeholder
                  - error_messages_for(@person)

            .row
              .col-lg-2
              .col-lg-8
                - if @person == current_person
                  .form-group
                    = p.label I18n.t('person.views.current_password'), for: 'person_current_password'
                    = p.password_field :current_password, class: 'form-control'

                .form-group
                  = p.label I18n.t('person.views.new_password'), for: 'person_password'
                  .pull-right
                    #password_strength.label
                  = p.password_field :password, value: @person.password, class: "strong_password form-control"

                .form-group
                  = p.label I18n.t('person.views.new_password_confirmation'), for: 'person_password_confirmation'
                  = p.password_field :password_confirmation, value: @person.password_confirmation, class: 'form-control'

                = p.hidden_field :email
              .col-lg-2

            .row
              .col-lg-12
                .pull-right
                  = p.submit I18n.t('person.views.update_password'), class: 'btn btn-primary'

                = link_to I18n.t("common.cancel"), person_path(@person), class: 'btn btn-default'


    .col-lg-3

app/views/people/map.html.haml
%nav.navbar.navbar-default.navbar-static-top.navbar-inverse{role: "navigation"}
  .row
    .navbar-header.col-md-1
      %span{class: 'navbar-brand', style: 'padding: 0 0 0 15px'}
        = image_tag 'logo_mini_white.png'

    .navbar-brand.col-md-11
      != @map[:title]


#map_container
  %input{type: 'hidden', name: 'map_markers', value: @map[:markers].to_json}
  %input{type: 'hidden', name: 'map_config', value: @map[:config].to_json}

- if @person
  .row
    .col-md-3
      %input{type: 'hidden', id: 'person_id', value: @person.id}
    .col-md-6
      %form.position
        .validation_errors_placeholder

        .form-group
          %label{for: 'person_geographic_coordinates'}
            = I18n.t("person.views.geographic_coordinates")
          .input-group
            %input{ id: 'person_geographic_coordinates',
                    class: 'form-control',
                    type: 'text',
                    value: @person.geographic_coordinates}
            .input-group-btn
              %button{type: 'submit',
                      name: 'update-person-geographic-coordinates',
                      class: 'btn btn-primary'}
                = I18n.t("common.update")
          %small.help-block
            = I18n.t("person.views.coordinates_format")
    .col-md-3

app/views/people/show.html.haml
- if params[:action] == 'paginate'
  #pagination.navbar.navbar-intermediate.navbar-default.navbar-static-top{style: 'margin-bottom: 0;'}
    .container
      .row
        .col-sm-1.col-xs-1.visible-sm.visible-xs
        .col-md-4.col-sm-3.col-xs-3
          - if @before
            .nav.navbar-nav.navbar-text

              = link_to paginate_people_path(query: @query.to_json, index: 0) do
                .icon-double-angle-left.icon-3x

              &nbsp;

              = link_to paginate_people_path(query: @query.to_json, index: @index - 1) do
                .icon-angle-left.icon-3x
                -# = @before.try(:name)

        .col-md-4.col-sm-4.col-xs-4.text-center
          .hidden-sm.hidden-xs
            %h2{style: 'margin: 8px 0 0 0;'}
              = link_to @person.name, @person, id: "pagination_title"
          .visible-sm.visible-xs
            %div{style: 'height: 27px;'} &nbsp;

          %h4{style: 'margin: 0 0 8px 0;'}= "#{@index + 1} / #{@total_entries}"

        .col-md-4.col-sm-3.col-xs-3
          - if @after
            .pull-right.nav.navbar-nav.navbar-text
              = link_to paginate_people_path(query: @query.to_json, index: @index + 1) do
                -#= @after.try(:name)
                .icon-angle-right.icon-3x

              &nbsp;

              = link_to paginate_people_path(query: @query.to_json, index: @total_entries - 1) do
                .icon-double-angle-right.icon-3x

        .col-sm-1.col-xs-1.visible-sm.visible-xs

= render partial: 'header'

= hidden_field :person, :id
- if flash[:error] or flash[:alert] or flash[:notice] or @person.errors.size > 0
  .row
    .col-lg-3
    .col-md-6
      - flash_messages
      - error_messages_for(@person)
    .col-lg-3

.main.container
  .tab-content
    #info_tab.tab-pane
      .row
        .col-lg-12.col-xl-8
          - if can? :read, @person
            #person{class: 'panel panel-primary', 'data-primary_panel' => "true"}
              .panel-heading
                .panel-title
                  = I18n.t('person.views.personal_information')

        .col-md-4
          - if can? :read, @person => PeoplePrivateTag and @person.id
            - if PrivateTag.count > 0
              #person_private_tags.panel.panel-default
                .panel-heading
                  .panel-title
                    = I18n.t('person.views.private_tags')
                    .pull-right.badge= @person.private_tags.empty? ? nil : @person.private_tags.count

        .col-md-4
          - if can? :read, @person => PeoplePublicTag and @person.id
            - if PublicTag.count > 0
              #person_public_tags.panel.panel-default
                .panel-heading
                  .panel-title
                    = I18n.t('person.views.public_tags')
                    .pull-right.badge= @person.public_tags.empty? ? nil : @person.public_tags.count

        .col-md-4
          - if can? :read, @person => PeopleCommunicationLanguage and @person.id
            #person_communication_languages.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('person.views.communication_languages')
                  .pull-right.badge= @person.communication_languages.empty? ? nil : @person.communication_languages.count

    #affairs_tab.tab-pane
      .row
        .col-md-12
          - if can? :read, @person => Affair
            #person_affairs{class: 'panel panel-primary ignore-affix', 'data-primary_panel' => "true"}
              .panel-heading
                .panel-title
                  = I18n.t('person.views.affairs')
                  .pull-right
                    .toggle-doc
              / .panel-body.main-doc

        .col-md-12
          - if can? :read, @person => Affair
            #person_affair_products.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('affair.views.products')

        .col-md-6
          - if can? :read, @person => Affair
            #person_affair_subscriptions.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('affair.views.subscriptions')

          - if can? :read, @person => TaskRate
            #person_affair_task_rates.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('task_rate.views.rates')

        .col-md-6
          - if can? :read, @person => Affair
            #person_affair_tasks.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('affair.views.tasks')

          - if can? :read, @person => Affair
            #person_affair_extras.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('affair.views.extras')

      .well
        #balance

      .row
        .col-md-6
          - if can? :read, @person => Invoice
            #person_affair_invoices.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('affair.views.invoices')

        .col-md-6
          - if can? :read, @person => Affair
            #person_affair_receipts.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('affair.views.receipts')

    #salaries_tab.tab-pane
      .row
        .col-md-6
          - if can? :manage, @person => Salaries::Salary
            #person_salaries.panel.panel-primary.ignore-affix
              .panel-heading
                .panel-title
                  = I18n.t('person.views.salaries')

        .col-md-6
          - if can? :manage, @person => EmploymentContract
            #person_employment_contracts.panel.panel-default.ignore-affix
              .panel-heading
                .panel-title
                  = I18n.t('person.views.employment_contracts')

          - if can? :statistics, Salaries::Salary
            #person_salaries_statistics
      .row
        .col-lg-12
          - if can? :manage, @person => Salaries::Salary
            .panel.panel-default.ignore-affix
              .panel-heading
                .panel-title
                  = I18n.t('person.views.salary_items')
              #person_salary_items

      .row
        .col-lg-12
          - if can? :manage, @person => Salaries::Salary
            .panel.panel-default.ignore-affix
              .panel-heading
                .panel-title
                  = I18n.t('person.views.salary_taxes')
              #person_salary_tax_datas

    #permissions_tab.tab-pane
      .row
        .col-md-6
          - if can? :manage, @person => PeopleRole
            #person_roles.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('person.views.roles')
        .col-md-6

    #activities_tab.tab-pane
      .row
        .col-md-6
          - if can? :manage, @person => Comment
            #person_comments.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('person.views.comments')

#affix.hidden-print
  %ul#info_affix.nav

  %ul#affairs_affix.nav
    %li= link_to t('common.summary'), "#person_affairs"

  %ul#salaries_affix.nav
    %li= link_to t('common.summary'), "#person_salaries"
    %li= link_to t('person.views.employment_contracts'), "#person_employment_contracts"
    %li= link_to t('person.views.salary_items'), "#person_salary_items"
    %li= link_to t('person.views.salary_taxes'), "#person_salary_tax_datas"
    %li= link_to t('person.views.statistics'), "#person_salaries_statistics"