config/routes.rb
CIRCL::Application.routes.draw do

  get 'requires_browser_update' => 'settings#requires_browser_update'

  unauthenticated :person do
    devise_scope :person do
      get "/" => "devise/sessions#new"
    end
  end

  authenticated :person do
    root :to => 'people#welcome'
  end

  devise_for :people
  resources  :people do
    member do
      get 'change_password', 'map'
      post 'update_password', 'unlock'
      put 'update_password'
    end

    collection do
      get 'paginate', 'search', 'title_search', 'nationality_search', 'duplicates_report'
    end

    resources :dashboard, :controller => 'people/dashboard', :only => :index do
      collection do
        get 'comments', 'activities', 'last_people_added', 'open_invoices', 'current_affairs',
          'open_salaries'
      end
    end

    resources :activities, :controller => 'people/activities'
    resources :histories, :controller => 'people/histories'

    resources :affairs, :controller => 'people/affairs' do
      collection do
        get 'search', 'count', 'affairs', 'invoices', 'receipts'
      end

      resources :extras, :controller => 'people/affairs/extras' do
        collection do
          get 'count', 'change_order'
        end
      end

      resources :invoices, :controller => 'people/affairs/invoices' do
        member do
          get 'bvr_preview'
        end

        collection do
          get 'search'
        end
      end

      resources :products, :controller => 'people/affairs/products' do
        collection do
          get 'search', 'change_position', 'categories'
          post 'reorder', 'group_update'
          delete 'group_destroy'
        end
      end

      resources :product_categories,
        controller: "people/affairs/product_categories",
        only: [:index] do

        collection do
          post 'update'
        end

      end

      resources :receipts,
        controller: 'people/affairs/receipts'

      delete 'communication_languages' => 'people/subscriptions#destroy' # Spine

      resources :subscriptions,
        controller: 'people/affairs/subscriptions'

      resources :tasks,
        controller: 'people/affairs/tasks'
    end

    resources :comments, :controller => 'people/comments' do
      collection do
        get 'count'
      end
    end

    put 'communication_languages' => 'people/communication_languages#update' # Spine
    resources :communication_languages, :controller => 'people/communication_languages', :only => :index do
    end

    resources :employment_contracts, :controller => 'people/employment_contracts'

    put 'private_tags' => 'people/private_tags#update' # Spine
    resources :private_tags, :controller => 'people/private_tags', :only => :index do
    end

    put 'public_tags' => 'people/public_tags#update' # Spine
    resources :public_tags, :controller => 'people/public_tags', :only => :index do
    end

    put 'roles' => 'people/roles#update' # Spine
    resources :roles, :controller => 'people/roles', :only => :index do
    end

    resources :salaries, :controller => 'people/salaries/salaries' do
      member do
        put 'update_items', 'update_tax_data'
      end

      collection do
        post 'statistics'
      end

      resources :items, :controller => 'people/salaries/items', :only => [ :index ] do
        member do
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end

      resources :tax_data, :controller => 'people/salaries/tax_data', :only => [ :index ] do
        member do
          put 'reset'
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end
    end

    resources :tasks, :controller => 'people/tasks'
  end

  get 'salaries' => 'salaries#index'
  namespace :salaries do
    resources :salaries, :except => [:edit] do
      member do
        post 'copy_reference'
      end
      collection do
        get 'pending', 'export', 'export_accounting', 'export_ocas', 'export_certificates', 'available_years'
      end
    end

    resources :taxes do
      member do
        post 'import_data'
      end
      collection do
        get 'models', 'count'
      end
    end
  end

  match 'directory' => 'directory#index', :via => [:get, :post]
  post 'directory/:id/mailchimp' => 'directory#mailchimp'
  get 'directory/map' => 'directory#map'
  post 'directory/confirm_people' => 'directory#confirm_people'
  post 'directory/import_people' => 'directory#import_people'
  namespace :directory do
    resources :query_presets
  end

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :affairs do
      collection do
        get 'search', 'available_statuses'
        post 'check_items', 'uncheck_items', 'archive_items'
      end
    end

    resources :bank_import_histories, :only => :index do
      collection do
        post 'confirm', 'import'
        get 'export'
      end
    end

    resources :creditors, defaults: { format: 'json' } do
      collection do
        get 'export', format: 'html'
        post 'check_items', 'uncheck_items', 'group_update'
        post 'preview_import', 'import', format: 'html'
        delete 'group_destroy'
      end
    end

    resources :invoices do
      collection do
        get 'export', 'available_statuses', 'search'
      end
    end

    resources :private_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :product_orders, only: [:index]

    resources :public_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :receipts do
      collection do
        get 'export', 'means_of_payments', 'documents'
        post 'documents'
      end
    end

    resources :subscriptions do
      member do
        # POST on show is required for the PDF generation from the search engine
        post 'add_members', 'transfer_overpaid_value', 'show', 'merge'
        delete 'remove_members'
      end
      collection do
        put 'tag_tool'
        get 'search', 'count'
      end
    end

  end

  resources :background_tasks, :only => [:index, :destroy]

  resources :settings, :only => :index do
    collection do
      get 'requires_browser_update'
    end
  end
  namespace :settings do
    resources :application_settings do
      collection do
        post 'restart'
      end
    end

    resources :affairs_conditions

    resources :currencies do
      collection do
        get 'search'
      end
    end

    resources :currency_rates do
      collection do
        get 'exchange'
      end
    end

    resources :generic_templates do
      collection do
        get 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :invoice_templates do
      collection do
        get 'placeholders', 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :jobs do
      collection do
        get 'search'
      end
    end

    resources :languages

    resources :ldap_attributes do
      collection do
        post 'synchronize'
      end
    end

    resources :locations do
      collection do
        get 'search'
      end
    end

    resources :permissions, :only => :index

    resources :products do
      collection do
        get 'search', 'count', 'category_search'
        post 'preview_import', 'import'
      end
      member do
        get 'programs'
      end
    end

    resources :product_programs do
      collection do
        get 'program_groups', 'program_group_search', 'search', 'count'
        post 'preview_import', 'import'
      end
    end

    resources :roles do
      resources :permissions, :controller => 'roles/permissions'
    end

    resources :search_attributes do
      collection do
        get 'searchable'
        post 'synchronize'
      end
    end

    # resources :tasks
    resources :task_types
    resources :task_rates

  end

  resources :permissions, :only => :index, :controller => 'people/permissions'

end

app/views/admin/_header.html.haml
#secondary_navbar.navbar.navbar-default.navbar-static-top

  .navbar-header
    .visible-xs
      .navbar-brand
        #tab_name

    // extra-small resolutions
    %button{class: 'navbar-toggle', 'data-toggle' => 'collapse', 'data-target' => '#secondary_navigation'}
      .icon-bar
      .icon-bar
      .icon-bar

  .container
    #secondary_navigation.collapse.navbar-collapse
      %ul#sub_nav.nav.navbar-nav
        - if can? :update, PrivateTag
          %li
            %a{href: '#tags_tab'}
              = I18n.t('admin.views.tags')

        - if can? :update, Affair
          %li
            %a{href: '#affairs_tab'}
              = I18n.t('admin.views.affairs')

        - if can? :update, Invoice
          %li
            %a{href: '#finances_tab'}
              = I18n.t('admin.views.finances')

        - if can? :update, ProductItem
          %li
            %a{href: '#products_tab'}
              = I18n.t('admin.views.products')

        - if can? :read, Creditor
          %li
            %a{href: '#creditors_tab'}
              = I18n.t('admin.views.creditors')

app/views/admin/confirm_people.html.haml
- # We use person.errors.empty? instead of person.valid? because it
- # resets the errors array every time and we filled it manually

= render :partial => 'header'

.container
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          .panel-title
            = I18n.t('admin.views.people_found_in_file')

        .panel-body
          != I18n.t('admin.views.people_import_help')

        - if @infos[:people].size > 0
          %table.datatable
            %thead
              %tr
                %th= I18n.t('admin.import.row')
                %th= I18n.t('person.views.first_name')
                %th= I18n.t('person.views.last_name')
                %th= I18n.t('common.title')
                %th= I18n.t('person.views.is_an_organization')
                %th= I18n.t('person.views.organization_name')
                %th= I18n.t('person.views.address')
                %th= I18n.t('person.views.location')
                %th= I18n.t('person.views.phone')
                %th= I18n.t('person.views.second_phone')
                %th= I18n.t('person.views.mobile')
                %th= I18n.t('person.views.email')
                %th= I18n.t('person.views.second_email')
                %th= I18n.t('person.views.job')
                %th= I18n.t('person.views.birth_date')
                %th= I18n.t('person.views.nationality')
                %th= I18n.t('person.views.avs_number')
                %th= I18n.t('person.views.bank_informations')
                %th= I18n.t('person.views.roles')
                %th= I18n.t('admin.import.main_communication_language')
                %th= I18n.t('person.views.communication_languages')
                %th= I18n.t('person.views.translation_aptitudes')
                %th= I18n.t('person.views.private_tags')
                %th= I18n.t('person.views.public_tags')
                %th= I18n.t('person.views.hidden')

            %tbody
              - @infos[:people].each_with_index do |person, i|
                - error_msg = []
                - person.errors.messages.each do |k,a|
                  - error_msg << a.join(", ")

                %tr{:class => (person.errors.empty? ? 'success' : 'danger'),
                  'data-trigger' => 'click',
                  'data-title' => (person.errors.size.to_s + " " + I18n.t("common.errors.error") + "(s)"),
                  'data-html' => true,
                  'data-placement' => 'auto top',
                  'data-content' => raw(error_msg.join(" | "))}

                  %td
                    = (i + 2)
                    - person.errors.messages.each do |k,a|
                      - a.each do |s|
                        = hidden_field_tag("people[][errors][#{k}][]", s)

                  %td= person.first_name
                  %td= person.last_name
                  %td= person.title
                  %td= I18n.t('common.' + person.is_an_organization.to_s)
                  %td= person.organization_name
                  %td= person.address
                  %td= relation_to_string(person.location)
                  %td= person.phone
                  %td= person.second_phone
                  %td= person.mobile
                  %td= person.email
                  %td= person.second_email
                  %td= relation_to_string(person.job)
                  %td= person.birth_date
                  %td= person.nationality
                  %td= person.avs_number
                  %td= person.bank_informations
                  %td= relation_to_string(person.roles)
                  %td= relation_to_string(person.main_communication_language)
                  %td= relation_to_string(person.communication_languages)
                  %td= relation_to_string(person.translation_aptitudes)
                  %td= relation_to_string(person.private_tags)
                  %td= relation_to_string(person.public_tags)
                  %td= I18n.t('common.' + person.hidden.to_s)

          - if ! @infos[:errors].empty?
            %h3= I18n.t('admin.views.people_file_errors')

            .alert.alert-danger
              - @infos[:errors].each do |line|
                = line

        - if @infos[:errors].empty?
          .panel-footer
            .text-right
              = form_tag(admin_import_people_path, :method => :post) do
                = submit_tag I18n.t('admin.views.proceed_with_import'), :class => 'btn btn-primary'

app/views/admin/index.html.haml
= render partial: 'header'

.container
  .row
    .col-lg-3
    .col-lg-6
      -# TODO put the right object below
      -#- error_messages_for(@admin)
      - flash_messages
    .col-lg-3

.main.container
  .tab-content
    #tags_tab.tab-pane
      .row
        .col-lg-6.col-md-6
          - if can? :update, PrivateTag
            #admin_private_tags.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.private_tags')

        .col-lg-6.col-md-6
          - if can? :update, PublicTag
            #admin_public_tags.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.public_tags')

    #affairs_tab.tab-pane
      .row
      .row
        .col-lg-12
          - if can? :update, Affair
            #admin_affairs.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.affairs')

        .col-lg-12
          - if can? :update, Subscription
            #admin_subscriptions.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.subscriptions')

    #finances_tab.tab-pane
      .row
        .col-lg-12
          - if can? :update, Receipt
            #admin_receipts.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.receipts')
      .row
        .col-lg-12
          - if can? :update, Invoice
            #admin_invoices.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.invoices')

    #products_tab.tab-pane
      .row
        .col-lg-12
          - if can? :update, ProductItem
            #admin_product_orders.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.product_orders')

    #creditors_tab.tab-pane
      .row
        .col-lg-12
          - if can? :read, Creditor
            #admin_creditors.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('admin.views.creditors')

#affix.hidden-print
  %ul#tags_affix.nav

  %ul#affairs_affix.nav

  %ul#finances_affix.nav

  / %ul#products_affix.nav

  / %ul#creditors_affix.nav