config/routes.rb
CIRCL::Application.routes.draw do

  get 'requires_browser_update' => 'settings#requires_browser_update'

  unauthenticated :person do
    devise_scope :person do
      get "/" => "devise/sessions#new"
    end
  end

  authenticated :person do
    root :to => 'people#welcome'
  end

  devise_for :people
  resources  :people do
    member do
      get 'change_password', 'map'
      post 'update_password', 'unlock'
      put 'update_password'
    end

    collection do
      get 'paginate', 'search', 'title_search', 'nationality_search', 'duplicates_report'
    end

    resources :dashboard, :controller => 'people/dashboard', :only => :index do
      collection do
        get 'comments', 'activities', 'last_people_added', 'open_invoices', 'current_affairs',
          'open_salaries'
      end
    end

    resources :activities, :controller => 'people/activities'
    resources :histories, :controller => 'people/histories'

    resources :affairs, :controller => 'people/affairs' do
      collection do
        get 'search', 'count', 'affairs', 'invoices', 'receipts'
      end

      resources :extras, :controller => 'people/affairs/extras' do
        collection do
          get 'count', 'change_order'
        end
      end

      resources :invoices, :controller => 'people/affairs/invoices' do
        member do
          get 'bvr_preview'
        end

        collection do
          get 'search'
        end
      end

      resources :products, :controller => 'people/affairs/products' do
        collection do
          get 'search', 'change_position', 'categories'
          post 'reorder', 'group_update'
          delete 'group_destroy'
        end
      end

      resources :product_categories,
        controller: "people/affairs/product_categories",
        only: [:index] do

        collection do
          post 'update'
        end

      end

      resources :receipts,
        controller: 'people/affairs/receipts'

      delete 'communication_languages' => 'people/subscriptions#destroy' # Spine

      resources :subscriptions,
        controller: 'people/affairs/subscriptions'

      resources :tasks,
        controller: 'people/affairs/tasks'
    end

    resources :comments, :controller => 'people/comments' do
      collection do
        get 'count'
      end
    end

    put 'communication_languages' => 'people/communication_languages#update' # Spine
    resources :communication_languages, :controller => 'people/communication_languages', :only => :index do
    end

    resources :employment_contracts, :controller => 'people/employment_contracts'

    put 'private_tags' => 'people/private_tags#update' # Spine
    resources :private_tags, :controller => 'people/private_tags', :only => :index do
    end

    put 'public_tags' => 'people/public_tags#update' # Spine
    resources :public_tags, :controller => 'people/public_tags', :only => :index do
    end

    put 'roles' => 'people/roles#update' # Spine
    resources :roles, :controller => 'people/roles', :only => :index do
    end

    resources :salaries, :controller => 'people/salaries/salaries' do
      member do
        put 'update_items', 'update_tax_data'
      end

      collection do
        post 'statistics'
      end

      resources :items, :controller => 'people/salaries/items', :only => [ :index ] do
        member do
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end

      resources :tax_data, :controller => 'people/salaries/tax_data', :only => [ :index ] do
        member do
          put 'reset'
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end
    end

    resources :tasks, :controller => 'people/tasks'
  end

  get 'salaries' => 'salaries#index'
  namespace :salaries do
    resources :salaries, :except => [:edit] do
      member do
        post 'copy_reference'
      end
      collection do
        get 'pending', 'export', 'export_accounting', 'export_ocas', 'export_certificates', 'available_years'
      end
    end

    resources :taxes do
      member do
        post 'import_data'
      end
      collection do
        get 'models', 'count'
      end
    end
  end

  match 'directory' => 'directory#index', :via => [:get, :post]
  post 'directory/:id/mailchimp' => 'directory#mailchimp'
  get 'directory/map' => 'directory#map'
  post 'directory/confirm_people' => 'directory#confirm_people'
  post 'directory/import_people' => 'directory#import_people'
  namespace :directory do
    resources :query_presets
  end

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :affairs do
      collection do
        get 'search', 'available_statuses'
        post 'check_items', 'uncheck_items', 'archive_items'
      end
    end

    resources :bank_import_histories, :only => :index do
      collection do
        post 'confirm', 'import'
        get 'export'
      end
    end

    resources :creditors, defaults: { format: 'json' } do
      collection do
        get 'export', format: 'html'
        post 'check_items', 'uncheck_items', 'group_update'
        post 'preview_import', 'import', format: 'html'
        delete 'group_destroy'
      end
    end

    resources :invoices do
      collection do
        get 'export', 'available_statuses', 'search'
      end
    end

    resources :private_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :product_orders, only: [:index]

    resources :public_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :receipts do
      collection do
        get 'export', 'means_of_payments', 'documents'
        post 'documents'
      end
    end

    resources :subscriptions do
      member do
        # POST on show is required for the PDF generation from the search engine
        post 'add_members', 'transfer_overpaid_value', 'show', 'merge'
        delete 'remove_members'
      end
      collection do
        put 'tag_tool'
        get 'search', 'count'
      end
    end

  end

  resources :background_tasks, :only => [:index, :destroy]

  resources :settings, :only => :index do
    collection do
      get 'requires_browser_update'
    end
  end
  namespace :settings do
    resources :application_settings do
      collection do
        post 'restart'
      end
    end

    resources :affairs_conditions

    resources :currencies do
      collection do
        get 'search'
      end
    end

    resources :currency_rates do
      collection do
        get 'exchange'
      end
    end

    resources :generic_templates do
      collection do
        get 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :invoice_templates do
      collection do
        get 'placeholders', 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :jobs do
      collection do
        get 'search'
      end
    end

    resources :languages

    resources :ldap_attributes do
      collection do
        post 'synchronize'
      end
    end

    resources :locations do
      collection do
        get 'search'
      end
    end

    resources :permissions, :only => :index

    resources :products do
      collection do
        get 'search', 'count', 'category_search'
        post 'preview_import', 'import'
      end
      member do
        get 'programs'
      end
    end

    resources :product_programs do
      collection do
        get 'program_groups', 'program_group_search', 'search', 'count'
        post 'preview_import', 'import'
      end
    end

    resources :roles do
      resources :permissions, :controller => 'roles/permissions'
    end

    resources :search_attributes do
      collection do
        get 'searchable'
        post 'synchronize'
      end
    end

    # resources :tasks
    resources :task_types
    resources :task_rates

  end

  resources :permissions, :only => :index, :controller => 'people/permissions'

end

app/controllers/settings/affairs_conditions_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class Settings::AffairsConditionsController < ApplicationController

  layout false

  load_and_authorize_resource

  def index
    @affairs_conditions = @affairs_conditions.actives if params[:actives]

    respond_to do |format|
      format.json { render json: @affairs_conditions }
    end
  end

  def show
    edit
  end

  def create
    @affairs_condition = AffairsCondition.new(affair_condition_params)
    respond_to do |format|
      if @affairs_condition.save
        format.json { render json: @affairs_condition }
      else
        format.json { render json: @affairs_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.json { render json: @affairs_condition }
    end
  end

  def update
    respond_to do |format|
      if @affairs_condition.update_attributes(affair_condition_params)
        format.json { render json: @affairs_condition }
      else
        format.json { render json: @affairs_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @affairs_condition.destroy
        format.json { render json: {} }
      else
        format.json { render json: @affairs_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def affair_condition_params
      params.require(:affair_condition).permit(
        :title,
        :description,
        :archive
      )
    end

end

app/controllers/settings/application_settings_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class Settings::ApplicationSettingsController < ApplicationController

  layout false

  load_and_authorize_resource

  def index
    default_currency = ApplicationSetting.value("default_currency")
    if Currency.where(iso_code: default_currency).count > 0
      h = { key: 'default_currency_details', value: Currency.where(iso_code: default_currency).first.attributes.to_json }
      @application_settings = @application_settings.to_a
      @application_settings << h
    end

    respond_to do |format|
      format.json { render json: @application_settings }
    end
  end

  def show
    edit
  end

  def create
    @application_setting = ApplicationSetting.new(application_setting_params)
    respond_to do |format|
      if @application_setting.save
        format.json { render json: @application_setting }
      else
        format.json { render json: @application_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.json { render json: @application_setting }
    end
  end

  def update
    respond_to do |format|
      if @application_setting.update_attributes(application_setting_params)
        format.json { render json: @application_setting }
      else
        format.json { render json: @application_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @application_setting.destroy
        format.json { render json: {} }
      else
        format.json { render json: @application_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def restart
    # Touch and wait...
    FileUtils.touch([Rails.root, "tmp/restart.txt"]).join("/")
    flash[:notice] = I18n.t("application_setting.notices.application_restarted")

    respond_to do |format|
      format.html { redirect_to settings_path(anchor: :advanced) }
    end
  end

  private

    def application_setting_params
      params.require(:application_setting).permit(
        :key,
        :value,
        :type_for_validation
      )
    end

end

app/controllers/settings/currencies_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class Settings::CurrenciesController < ApplicationController

  layout false

  load_and_authorize_resource

  def index
    respond_to do |format|
      format.json do
        render json: @currencies
      end
    end
  end

  def show
    edit
  end

  def create
    @currency = Currency.new(currency_params)
    respond_to do |format|
      if @currency.save
        format.json do
          render json: @currency
        end
      else
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.json { render json: @currency }
    end
  end

  def update
    respond_to do |format|
      if @currency.update_attributes(currency_params)
        format.json do
          render json: @currency
        end
      else
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @currency.destroy
        format.json { render json: {} }
      else
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    if params[:term].blank?
      results = []
    else
      param = params[:term].to_s.gsub('\\'){ '\\\\' } # We use the block form otherwise we need 8 backslashes
      results = @currencies.where("currencies.iso_code ~* ? OR
        currencies.name ~* ? OR
        currencies.iso_numeric ~* ?",
        *([param] * 3)).limit(10)
    end

    respond_to do |format|
      format.json { render json: results.map{ |p| { label: p.iso_code, desc: p.name, id: p.id }}}
    end
  end

  private

    def currency_params
      params.require(:currency).permit(
        :priority,
        :iso_code,
        :iso_numeric,
        :name,
        :symbol,
        :subunit,
        :subunit_to_unit,
        :separator,
        :delimiter
      )
    end

end

app/controllers/settings/languages_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

class Settings::LanguagesController < ApplicationController

  layout false

  load_and_authorize_resource

  def index
    respond_to do |format|
      format.json { render json: @languages }
    end
  end

  def show
    edit
  end

  def create
    @language = Language.new(language_params)
    respond_to do |format|
      if @language.save
        format.json  { render json: @language }
      else
        format.json  { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.json  { render json: @language }
    end
  end

  def update
    respond_to do |format|
      if @language.update_attributes(language_params)
        format.json  { render json: @language }
      else
        format.json  { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @language.destroy
        format.json  { render json: {} }
      else
        format.json  { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def language_params
      params.require(:language).permit(:name, :code)
    end

end

app/views/settings/index.html.haml
#secondary_navbar.navbar.navbar-default.navbar-static-top

  .navbar-header
    .visible-xs
      .navbar-brand
        #tab_name

    // extra-small resolutions
    %button{class: 'navbar-toggle', 'data-toggle' => 'collapse', 'data-target' => '#secondary_navigation'}
      .icon-bar
      .icon-bar
      .icon-bar

  .container
    #secondary_navigation.collapse.navbar-collapse
      %ul#sub_nav.nav.navbar-nav
        - if can? :manage, Language
          %li
            %a{href: '#properties_tab'}
              = I18n.t('settings.views.attributes')

        - if can? :manage, InvoiceTemplate
          %li
            %a{href: '#templates_tab'}
              = I18n.t('settings.views.templates')

        - if can? :manage, SearchAttribute
          %li
            %a{href: '#searchengine_tab'}
              = I18n.t('settings.views.search_engine')

        - if can? :manage, Role
          %li
            %a{href: '#privileges_tab'}
              = I18n.t('settings.views.privileges')

        - if can? :manage, Affair
          %li
            %a{href: '#affairs_tab'}
              = I18n.t('settings.views.affairs')

        - if can? :manage, Currency
          %li
            %a{href: '#currencies_tab'}
              = I18n.t('settings.views.currencies')

        - if can? :manage, ApplicationSetting
          %li
            %a{href: '#database_tab'}
              = I18n.t('settings.views.database')

        - if can? :manage, ApplicationSetting
          %li
            %a{href: '#advanced_tab'}
              = I18n.t('settings.views.advanced')

.container
  .row
    .col-lg-3
    .col-lg-6
      -# TODO put the right object below
      -#- error_messages_for(@settings)
      - flash_messages
    .col-lg-3

.main.container
  .tab-content
    #properties_tab.tab-pane.fade
      .row
        .col-md-6
          - if can? :update, Location
            #settings_locations.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.locations')

        .col-md-6
          - if can? :update, Job
            #settings_jobs.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.jobs')

      .row
        .col-md-6
          - if can? :update, Language
            #settings_languages.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.languages')

        .col-md-6

    #templates_tab.tab-pane.fade
      .row
        .col-md-6
          - if can? :update, InvoiceTemplate
            #settings_invoice_templates.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.invoice_templates')

        .col-md-6
          - if can? :update, GenericTemplate
            #settings_generic_templates.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.generic_templates')


    #searchengine_tab.tab-pane.fade
      .row
        .col-md-6
          - if can? :update, SearchAttribute
            #settings_search_attributes.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.search_attributes')

          - if can? :mailchimp, Directory
            #settings_mailchimp.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.mailchimp')

              - if @mailchimp_lists
                .panel-body
                  .row
                    .form-inline.col-lg-12

                      .alert.alert-info
                        = I18n.t("settings.views.select_list_and_click_synchronize")

                      .form-group
                        %select{name: 'list', id: "mailchimp_lists", class: 'form-control'}
                          - @mailchimp_lists.each_pair do |id, name|
                            %option{value: id}= name

                        .icon-chevron-right

                        %button.btn.btn-default{name: 'synchronize_mailchimp'}
                          .icon-refresh
                          .hidden-inline-xs
                            = I18n.t('common.synchronize')
              - else
                .panel-body
                  .alert.alert-warning
                    != I18n.t("settings.views.mailchimp_configuration_required")
                    %br
                    .pull-right
                      = link_to t("settings.views.advanced"),
                        settings_path(anchor: :advanced),
                        class: 'btn btn-warning',
                        onclick: '$("a[href=#advanced_tab]").click()'
                    .clearfix



    #privileges_tab.tab-pane.fade
      .row
        .col-md-6
          - if can? :update, Role
            #settings_roles.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.roles')
        .col-md-6
          - if can? :update, Role
            #settings_role_permissions.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('role.views.permissions')

    #affairs_tab.tab-pane.fade
      .row
        .col-md-6
          - if can? :manage, TaskType
            #settings_task_types.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.task_types')

          - if can? :manage, TaskRate
            #settings_task_rates.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.task_rates')

          - if can? :manage, AffairsCondition
            #settings_conditions.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.affairs_conditions')

        .col-md-6
          - if can? :manage, Product
            #settings_products.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.products')

          - if can? :manage, ProductProgram
            #settings_product_programs.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.product_programs')

    #currencies_tab.tab-pane.fade
      .row
        .col-lg-6
          - if can? :update, Currency
            #settings_currencies.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.currencies')
        .col-lg-6
          - if can? :update, CurrencyRate
            #settings_currency_rates.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.currency_rates')

    #database_tab.tab-pane.fade
      .row
        .col-lg-6
          - if can? :manage, Person
            = render partial: 'settings/database/people'

          - if can? :manage, Product
            = render partial: 'settings/database/products'

          - if can? :manage, ProductProgram
            = render partial: 'settings/database/product_programs'

        .col-lg-6
          - if can? :manage, Creditor
            = render partial: 'settings/database/creditors'


    #advanced_tab.tab-pane.fade
      .row
        .col-lg-6
          - if can? :update, ApplicationSetting
            #settings_application_settings.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.application_settings')
        .col-lg-6
          - if can? :restart, ApplicationSetting
            #settings_application_settings.panel.panel-default
              .panel-heading
                .panel-title
                  = I18n.t('settings.views.restart_application')
              .panel-body
                .alert.alert-warning
                  != I18n.t("application_setting.notices.restart_warning")

                = form_tag restart_settings_application_settings_path do
                  %center
                    %button{ type: "submit",
                      "data-confirm" => I18n.t("common.are_you_sure"),
                      rel: 'nofollow',
                      class: 'btn btn btn-danger' }
                      = I18n.t("application_setting.views.restart")

#affix.hidden-print
  %ul#properties_affix.nav
  %ul#templates_affix.nav
  %ul#searchengine_affix.nav
  %ul#privileges_affix.nav
  %ul#affairs_affix.nav
  %ul#currencies_affix.nav
  %ul#database_affix.nav
  %ul#advanced_affix.nav

app/views/settings/requires_browser_update.html.haml
!!! Strict
%html
%head
  %title
    = "CIRCL: " + I18n.t("common.requires_browser_update")
  %style{ type: "text/css" }
    :sass
      body
        font-family: "Open Sans", Arial
        font-size: 14px
        text-align: center

      img
        border: none

      .browsers_compatibility
        table
          width: 512px
          margin: 50px auto
%body
  .browsers_compatibility
    %h1= I18n.t("common.requires_browser_update")
    = I18n.t("common.browser.a_modern_browser_is_required")
    %h2= I18n.t("common.browser.currently_supported_browser_are") + ":"

    // = I18n.t("common.browser.multiplateform_browsers")

    %table
      %tr
        %td
          = link_to image_tag('browsers/chrome.png'), "http://www.google.com/chrome", target: '_blank', title: 'Chrome'
        %td
          = link_to image_tag('browsers/firefox.png'), "http://www.mozilla.org/firefox", target: '_blank', title: 'Firefox'

      %tr
        %td
          = link_to image_tag('browsers/opera.png'), "http://www.opera.com", target: '_blank', title: 'Opera'
        %td
          = link_to image_tag('browsers/konqueror.png'), "http://www.konqueror.org/", target: '_blank', title: 'Konqueror'

    // = I18n.t("common.browser.mobile_browsers")