config/routes.rb
CIRCL::Application.routes.draw do

  get 'requires_browser_update' => 'settings#requires_browser_update'

  unauthenticated :person do
    devise_scope :person do
      get "/" => "devise/sessions#new"
    end
  end

  authenticated :person do
    root :to => 'people#welcome'
  end

  devise_for :people
  resources  :people do
    member do
      get 'change_password', 'map'
      post 'update_password', 'unlock'
      put 'update_password'
    end

    collection do
      get 'paginate', 'search', 'title_search', 'nationality_search', 'duplicates_report'
    end

    resources :dashboard, :controller => 'people/dashboard', :only => :index do
      collection do
        get 'comments', 'activities', 'last_people_added', 'open_invoices', 'current_affairs',
          'open_salaries'
      end
    end

    resources :activities, :controller => 'people/activities'
    resources :histories, :controller => 'people/histories'

    resources :affairs, :controller => 'people/affairs' do
      collection do
        get 'search', 'count', 'affairs', 'invoices', 'receipts'
      end

      resources :extras, :controller => 'people/affairs/extras' do
        collection do
          get 'count', 'change_order'
        end
      end

      resources :invoices, :controller => 'people/affairs/invoices' do
        member do
          get 'bvr_preview'
        end

        collection do
          get 'search'
        end
      end

      resources :products, :controller => 'people/affairs/products' do
        collection do
          get 'search', 'change_position', 'categories'
          post 'reorder', 'group_update'
          delete 'group_destroy'
        end
      end

      resources :product_categories,
        controller: "people/affairs/product_categories",
        only: [:index] do

        collection do
          post 'update'
        end

      end

      resources :receipts,
        controller: 'people/affairs/receipts'

      delete 'communication_languages' => 'people/subscriptions#destroy' # Spine

      resources :subscriptions,
        controller: 'people/affairs/subscriptions'

      resources :tasks,
        controller: 'people/affairs/tasks'
    end

    resources :comments, :controller => 'people/comments' do
      collection do
        get 'count'
      end
    end

    put 'communication_languages' => 'people/communication_languages#update' # Spine
    resources :communication_languages, :controller => 'people/communication_languages', :only => :index do
    end

    resources :employment_contracts, :controller => 'people/employment_contracts'

    put 'private_tags' => 'people/private_tags#update' # Spine
    resources :private_tags, :controller => 'people/private_tags', :only => :index do
    end

    put 'public_tags' => 'people/public_tags#update' # Spine
    resources :public_tags, :controller => 'people/public_tags', :only => :index do
    end

    put 'roles' => 'people/roles#update' # Spine
    resources :roles, :controller => 'people/roles', :only => :index do
    end

    resources :salaries, :controller => 'people/salaries/salaries' do
      member do
        put 'update_items', 'update_tax_data'
      end

      collection do
        post 'statistics'
      end

      resources :items, :controller => 'people/salaries/items', :only => [ :index ] do
        member do
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end

      resources :tax_data, :controller => 'people/salaries/tax_data', :only => [ :index ] do
        member do
          put 'reset'
          get 'compute_value_for_next_salaries', 'compute_value_for_this_salary'
        end
      end
    end

    resources :tasks, :controller => 'people/tasks'
  end

  get 'salaries' => 'salaries#index'
  namespace :salaries do
    resources :salaries, :except => [:edit] do
      member do
        post 'copy_reference'
      end
      collection do
        get 'pending', 'export', 'export_accounting', 'export_ocas', 'export_certificates', 'available_years'
      end
    end

    resources :taxes do
      member do
        post 'import_data'
      end
      collection do
        get 'models', 'count'
      end
    end
  end

  match 'directory' => 'directory#index', :via => [:get, :post]
  post 'directory/:id/mailchimp' => 'directory#mailchimp'
  get 'directory/map' => 'directory#map'
  post 'directory/confirm_people' => 'directory#confirm_people'
  post 'directory/import_people' => 'directory#import_people'
  namespace :directory do
    resources :query_presets
  end

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :affairs do
      collection do
        get 'search', 'available_statuses'
        post 'check_items', 'uncheck_items', 'archive_items'
      end
    end

    resources :bank_import_histories, :only => :index do
      collection do
        post 'confirm', 'import'
        get 'export'
      end
    end

    resources :creditors, defaults: { format: 'json' } do
      collection do
        get 'export', format: 'html'
        post 'check_items', 'uncheck_items', 'group_update'
        post 'preview_import', 'import', format: 'html'
        delete 'group_destroy'
      end
    end

    resources :invoices do
      collection do
        get 'export', 'available_statuses', 'search'
      end
    end

    resources :private_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :product_orders, only: [:index]

    resources :public_tags do
      member do
        post 'add_members', 'remove_all_members'
      end
      collection do
        get 'search'
      end
    end

    resources :receipts do
      collection do
        get 'export', 'means_of_payments', 'documents'
        post 'documents'
      end
    end

    resources :subscriptions do
      member do
        # POST on show is required for the PDF generation from the search engine
        post 'add_members', 'transfer_overpaid_value', 'show', 'merge'
        delete 'remove_members'
      end
      collection do
        put 'tag_tool'
        get 'search', 'count'
      end
    end

  end

  resources :background_tasks, :only => [:index, :destroy]

  resources :settings, :only => :index do
    collection do
      get 'requires_browser_update'
    end
  end
  namespace :settings do
    resources :application_settings do
      collection do
        post 'restart'
      end
    end

    resources :affairs_conditions

    resources :currencies do
      collection do
        get 'search'
      end
    end

    resources :currency_rates do
      collection do
        get 'exchange'
      end
    end

    resources :generic_templates do
      collection do
        get 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :invoice_templates do
      collection do
        get 'placeholders', 'count'
      end
      member do
        post 'upload_odt'
      end
    end

    resources :jobs do
      collection do
        get 'search'
      end
    end

    resources :languages

    resources :ldap_attributes do
      collection do
        post 'synchronize'
      end
    end

    resources :locations do
      collection do
        get 'search'
      end
    end

    resources :permissions, :only => :index

    resources :products do
      collection do
        get 'search', 'count', 'category_search'
        post 'preview_import', 'import'
      end
      member do
        get 'programs'
      end
    end

    resources :product_programs do
      collection do
        get 'program_groups', 'program_group_search', 'search', 'count'
        post 'preview_import', 'import'
      end
    end

    resources :roles do
      resources :permissions, :controller => 'roles/permissions'
    end

    resources :search_attributes do
      collection do
        get 'searchable'
        post 'synchronize'
      end
    end

    # resources :tasks
    resources :task_types
    resources :task_rates

  end

  resources :permissions, :only => :index, :controller => 'people/permissions'

end

app/controllers/people/affairs/products_controller.rb
=begin
  CIRCL Directory
  Copyright (C) 2011 Complex IT sàrl

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
=end

# TODO Rename product in item to prevent confusion

class People::Affairs::ProductsController < ApplicationController

  layout false

  before_action do
    @person = Person.find params[:person_id]
    @affair = Affair.find params[:affair_id]
  end

  def index
    authorize! :read, @person => ProductItem

    params[:items] = JSON.parse(params[:items]) if params[:items]

    if params[:items] and not params[:items].blank? and not params[:export_all]
      @products = @affair.product_items.where(id:params[:items])
    else
      @products = @affair.product_items
    end

    if @products.count > 0
      reference = @products.first
    else
      reference = @affair.product_items.first
    end

    if params[:template_id]
      reference.template = GenericTemplate.find params[:template_id]
    end

    respond_to do |format|
      format.json { render json: @products }

      format.csv do
        fields = []
        fields << 'position'
        fields << 'parent.try(:position)'
        fields << 'category.try(:title)'
        fields << 'category.try(:position)'
        fields << 'parent.try(:product).try(:key)'
        fields << 'quantity'
        fields << 'product.key'
        fields << 'product.title'
        fields << 'program.description'
        fields << 'program.key'
        fields << 'program.title'
        fields << 'program.description'
        fields << 'value'
        render inline: csv_ify(@products, fields)
      end

      if params[:template_id]
        format.html do
          generator = AttachmentGenerator.new(@products, reference)
          render inline: generator.html, layout: 'preview'
        end

        format.pdf do
          @pdf = ""
          generator = AttachmentGenerator.new(@products, reference)
          generator.pdf { |o,pdf| @pdf = pdf.read }
          send_data @pdf,
                    filename: "affair_products_#{params[:affair_id]}.pdf",
                    type: 'application/pdf'
        end

        format.odt do
          @odt = ""
          generator = AttachmentGenerator.new(@products, reference)
          generator.odt { |o,odt| @odt = odt.read }
          send_data @odt,
                    filename: "affair_products_#{params[:affair_id]}.odt",
                    type: 'application/vnd.oasis.opendocument.text'
        end
      end
    end
  end

  def show
    edit
  end

  def create
    authorize! :create, @person => ProductItem

    # If @affair.product_items << OBJ is used, then update_on_prestation_alteration is called
    # which will fail as long as the product item is not saved.
    params[:affair_id] = @affair.id
    @product = ProductItem.new(product_params)

    respond_to do |format|
      if @product.save
        # Triggered manually here
        @affair.update_on_prestation_alteration
        format.json { render json: @product }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize! :read, @person => ProductItem

    @product = @affair.product_items.find(params[:id])

    respond_to do |format|
      format.json { render json: @product }
    end
  end

  def update
    authorize! :update, @person => ProductItem

    @product = @affair.product_items.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(product_params)
        format.json { render json: @product }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def group_update
    authorize! :update, @person => ProductItem

    errors = nil
    success = false

    @affair.product_items.transaction do
      @products = @affair.product_items.find(params[:ids])

      params = product_params

      @products.each do |p|
        p.update_attributes params

        if p.errors.size > 0
          errors = p.errors
          raise ActiveRecord::Rollback
        end
      end

      success = true
    end

    respond_to do |format|
      if success
        format.json { render json: @products }
      else
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @person => ProductItem

    @product = @affair.product_items.find(params[:id])

    respond_to do |format|
      if @product.destroy
        format.json { render json: {} }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def group_destroy
    authorize! :destroy, @person => ProductItem

    errors = nil
    success = false

    @affair.product_items.transaction do
      @products = @affair.product_items.where(id: params[:ids])
      success = @products.destroy_all
    end

    respond_to do |format|
      if success
        format.json { render json: @products }
      else
        format.json { render json: I18n.t("common.errors.failed_to_destroy"), status: :unprocessable_entity }
      end
    end
  end

  def search
    authorize! :read, @person => ProductItem

    hash = {}
    if ! params[:term].blank?
      result = []
      param = params[:term].to_s.gsub('\\'){ '\\\\' } # We use the block form otherwise we need 8 backslashes
      result = Product
        .joins(:product_items)
        .where("product_items.affair_id = ?", @affair.id)

      if param.is_i?
        result = result.where("product_items.position = ?", param)
      else
        result = result.where("products.key ~* ? OR products.title ~* ?", *([param]*2))
      end

      if result
        hashes = result.map{ |t|
          @affair.product_items.where(product_id: t.id).map do |pi|
            unless pi.parent
              {
                id: pi.try(:id),
                label: t.key,
                title: t.title,
                description: t.description,
                desc: "position: " + pi.try(:position).try(:to_s)
              }
            end
          end
        }
        hashes = hashes.flatten.uniq
        hashes.delete(nil)
      end
    end

    respond_to do |format|
      format.json { render json: hashes }
    end
  end

  def categories
    authorize! :read, @person => ProductItem

    hash = {}
    if ! params[:term].blank?
      param = params[:term].to_s.gsub('\\'){ '\\\\' } # We use the block form otherwise we need 8 backslashes

      result = @affair.product_categories.where("title ~ ?", param)

      if result
        hash = result.map{ |t| {label: t.title} }
      end
    end

    respond_to do |format|
      format.json { render json: hash }
    end
  end

  def change_position
    authorize! :update, @person => ProductItem
    @product = ProductItem.find(params[:id])

    # send table index position
    success = @product.update_table_index_position(params[:toPosition].to_i - 1)
    # success = ProductItem.update_position(@product.id, params[:fromPosition].to_i, params[:toPosition].to_i)

    respond_to do |format|
      if success
        format.json { render json: @affair.product_items.all }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def reorder
    authorize! :update, @person => ProductItem

    success = @affair.reorder_product_items!


    respond_to do |format|
      if success
        format.json { render json: @affair.product_items.all }
      else
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # FIXME: Ensure affair is accessible by person
  def product_params
    params[:value_currency] = ApplicationSetting.value("default_currency") if params[:value_currency].blank?

    category = params[:category]
    if ! category.blank?
      cat = @affair.product_categories.where(title: category).first
      cat ||= @affair.product_categories.create!(title: category)
      params[:category_id] = cat.id
    end
    params.delete(:category)

    p = params.permit(
        :parent_id,
        :program_id,
        :product_id,
        :affair_id,
        :category_id,
        :value,
        :value_currency,
        :position,
        :bid_percentage,
        :quantity,
        :comment,
        :ordered_at,
        :confirmed_at,
        :delivery_at,
        :warranty_begin,
        :warranty_end,
        :category_id,
        :ids
      )

    p
  end

end

app/views/settings/products/preview_import.html.haml
#secondary_navbar.navbar.navbar-default.navbar-static-top

  .container
    #secondary_navigation.collapse.navbar-collapse
      .navbar-brand
        = I18n.t("product.views.import_products")

.container
  .row
    .col-lg-12
      - if @products.is_a? String
        .alert.alert-danger
          = link_to settings_path(anchor: 'affairs'), class: 'btn btn-primary' do
            .icon.icon-chevron-left
            = I18n.t("common.previous")
          = @products

      - else
        = form_tag(import_settings_products_path, method: :post, id: 'settings_products_import') do
          .panel.panel-default
            .panel-heading
              .panel-title
                = I18n.t('product.views.products_found_in_file')

            .panel-body

              %table.datatable
                %thead
                  %tr
                    %th= I18n.t("common.line")
                    %th= I18n.t("common.key")
                    %th= I18n.t("common.title")
                    %th= I18n.t("common.description")
                    %th.number= I18n.t("common.width")
                    %th.number= I18n.t("common.height")
                    %th.number= I18n.t("common.depth")
                    %th.number= I18n.t("common.volume")
                    %th.number= I18n.t("common.weight")
                    %th= I18n.t("product.views.unit_symbol")
                    %th= I18n.t("product.views.price_to_unit_rate")

                    %th.number= I18n.t("product.views.buying_prices")
                    %th.number= I18n.t("product.views.selling_prices")
                    %th.number= I18n.t("product.views.art_values")
                    %th.number= I18n.t("product.views.program_groups")

                    %th= I18n.t("product.views.provider_id")
                    %th= I18n.t("product.views.after_sale_id")
                    %th= I18n.t("common.category")
                    %th= I18n.t("product.views.has_accessories")
                    %th= I18n.t("common.archive")
                    %th= I18n.t("common.import")

                %tbody
                  - @products.each_with_index do |p, i|
                    - line = i + 1
                    - error_msg = []
                    - p.errors.messages.each do |k,a|
                      - error_msg << "#{k}: " + a.join(", ")

                    - p.notices.messages.each do |k,a|
                      - error_msg << a.join(", ")

                    - classes = []
                    - if p.errors.empty?
                      - if p.notices.empty?
                        - classes << 'success'
                      - else
                        - classes << 'warning'
                    - else
                      - classes << 'danger'

                    %tr{class: classes.join(" "),
                      'data-trigger' => 'click',
                      'data-title' => (p.errors.size.to_s + " " + I18n.t("common.errors.error") + "(s)"),
                      'data-html' => true,
                      'data-placement' => 'auto center',
                      'data-container' => "body",
                      'data-line' => line,
                      'data-content' => raw(error_msg.join(" | "))}

                      %td= line
                      %td= p.key
                      %td= p.title
                      %td= p.description.try(:exerpt)
                      %td.number= p.width
                      %td.number= p.height
                      %td.number= p.depth
                      %td.number= p.volume
                      %td.number= p.weight
                      %td= p.unit_symbol
                      %td= p.price_to_unit_rate

                      - # count won't work for preview as record is not saved
                      - if p.variants.size > 0
                        %td.number
                          != p.variants.map{|v| v.buying_price.try(:to_view)}.join("<br />")
                        %td.number
                          != p.variants.map{|v| v.selling_price.try(:to_view)}.join("<br />")
                        %td.number
                          != p.variants.map{|v| v.art.try(:to_view)}.join("<br />")
                        %td.number
                          != p.variants.map{|v| v.program_group}.sort.join("<br />")
                      - else
                        %td.number
                        %td.number
                        %td.number
                        %td.number

                      %td= p.provider.try(:name)
                      %td= p.after_sale.try(:name)
                      %td= p.category
                      %td
                        = I18n.t("common.#{p.has_accessories}") unless p.has_accessories.nil?
                      %td
                        = I18n.t("common.#{p.archive}") unless p.archive.nil?
                      %td= check_box_tag "unreal[]", i, p.errors.count == 0

              %h3= I18n.t("product.views.ignore_theses_columns")
              .row
                .col-md-6
                  %h4= I18n.t("product.views.product_attributes")
                  %table.table.table-hover
                    .thead
                      %tr
                        %td= t("product.views.attribute")
                        %td
                    .tbody
                      %tr
                        %td
                          key
                        %td
                          = check_box_tag "skip_columns[]", 'key', false, disabled: true
                      - @columns.each do |c|
                        - next if c == :key # Mandatory
                        - next if c.to_s.match(/\d+$/) # Skip prices
                        %tr
                          %td
                            = c
                          %td
                            = check_box_tag "skip_columns[]", c

                .col-md-6
                  %h4= I18n.t("product.views.price_definitions")
                  %table.table.table-hover
                    .thead
                      %tr
                        %td
                        %td
                          %label
                            %input.select_all{type: 'checkbox', name: 'program_group'}
                            = t("product.views.program_group")
                        %td
                          %label
                            %input.select_all{type: 'checkbox', name: 'buying_price'}
                            = t("product.views.buying_price")
                        %td
                          %label
                            %input.select_all{type: 'checkbox', name: 'selling_price'}
                            = t("product.views.selling_price")
                        %td
                          %label
                            %input.select_all{type: 'checkbox', name: 'art'}
                            = t("product.views.art")
                    .tbody
                      - (1..16).each do |row|
                        %tr
                          %td
                            = row
                          - %w(program_group buying_price selling_price art).each do |col|
                            %td{class: col}
                              = check_box_tag "skip_columns[]", [col, row].join("_")

              %h3= I18n.t("product.views.options")

              .checkbox
                %label{for: 'person_remember_me', class: 'inline'}
                  = check_box_tag "clear_variants", 1
                  = I18n.t('product.views.clear_variants')

            .panel-footer
              .text-right
                = submit_tag I18n.t('product.views.proceed_with_import'), class: 'btn btn-primary'